/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsale;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author yanti
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
        String ID = login.getUserLogin();
        String level = login.getLevel();
        label_nama.setText(ID);
        label_level.setText(level);
        Level();
        tanggal();
    }
    
    public void tanggal(){
        Date ys=new Date();
        SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd");
        label_tanggal.setText(s.format(ys));
    }
    
    private void Level(){ 
        if (label_level.getText().equals("Admin")){
            button_databarang.setEnabled(true);
            button_datatransaksi.setEnabled(true);
            button_transaksi.setEnabled(true);
            button_datasupplier.setEnabled(true);
            button_datapengguna.setEnabled(true);
            button_databarangmasuk.setEnabled(true);
            button_databarangkeluar.setEnabled(true);
            button_opsi.setEnabled(true); 

        }
        else if (label_level.getText().equals("Gudang")) {
            button_databarang.setEnabled(true);
            button_datatransaksi.setEnabled(false);
            button_transaksi.setEnabled(false);
            button_datasupplier.setEnabled(false);
            button_datapengguna.setEnabled(false);
            button_databarangmasuk.setEnabled(false);
            button_databarangkeluar.setEnabled(false);
            button_opsi.setEnabled(false); 
        }
        else if (label_level.getText().equals("Kasir")) {
            button_databarang.setEnabled(false);
            button_datatransaksi.setEnabled(false);
            button_transaksi.setEnabled(true);
            button_datasupplier.setEnabled(false);
            button_datapengguna.setEnabled(false);
            button_databarangmasuk.setEnabled(false);
            button_databarangkeluar.setEnabled(false);
            button_opsi.setEnabled(false); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        button_logout = new javax.swing.JButton();
        button_datasupplier = new javax.swing.JButton();
        button_datatransaksi = new javax.swing.JButton();
        button_databarang = new javax.swing.JButton();
        button_transaksi = new javax.swing.JButton();
        button_datapengguna = new javax.swing.JButton();
        label_nama = new javax.swing.JLabel();
        label_tanggal = new javax.swing.JLabel();
        button_databarangmasuk = new javax.swing.JButton();
        button_databarangkeluar = new javax.swing.JButton();
        label_level = new javax.swing.JLabel();
        button_opsi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        button_logout.setFont(new java.awt.Font("TeXGyreAdventor", 1, 18)); // NOI18N
        button_logout.setText("Log Out");
        button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutActionPerformed(evt);
            }
        });

        button_datasupplier.setFont(new java.awt.Font("TeXGyreAdventor", 1, 18)); // NOI18N
        button_datasupplier.setText("Data Supplier");
        button_datasupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_datasupplierActionPerformed(evt);
            }
        });

        button_datatransaksi.setFont(new java.awt.Font("TeXGyreAdventor", 1, 18)); // NOI18N
        button_datatransaksi.setText("Data Transaksi");
        button_datatransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_datatransaksiActionPerformed(evt);
            }
        });

        button_databarang.setFont(new java.awt.Font("TeXGyreAdventor", 1, 18)); // NOI18N
        button_databarang.setText("Data Barang");
        button_databarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_databarangActionPerformed(evt);
            }
        });

        button_transaksi.setFont(new java.awt.Font("TeXGyreAdventor", 1, 18)); // NOI18N
        button_transaksi.setText("Transaksi");
        button_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_transaksiActionPerformed(evt);
            }
        });

        button_datapengguna.setFont(new java.awt.Font("TeXGyreAdventor", 1, 18)); // NOI18N
        button_datapengguna.setText("Data Pengguna");
        button_datapengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_datapenggunaActionPerformed(evt);
            }
        });

        label_nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_nama.setText("Nama");

        label_tanggal.setText("Tanggal");

        button_databarangmasuk.setFont(new java.awt.Font("TeXGyreAdventor", 1, 18)); // NOI18N
        button_databarangmasuk.setText("Data Barang Masuk");
        button_databarangmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_databarangmasukActionPerformed(evt);
            }
        });

        button_databarangkeluar.setFont(new java.awt.Font("TeXGyreAdventor", 1, 18)); // NOI18N
        button_databarangkeluar.setText("Data Barang Keluar");
        button_databarangkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_databarangkeluarActionPerformed(evt);
            }
        });

        label_level.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_level.setText("Level");

        button_opsi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button_opsi.setText("Opsi Pembayaran");
        button_opsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_opsiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_datasupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_databarangmasuk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_databarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_databarangkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_datapengguna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_datatransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(button_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                            .addComponent(button_opsi, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_level)
                            .addComponent(label_nama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_tanggal)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_nama)
                    .addComponent(label_tanggal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_level)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_datatransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_databarang, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_opsi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_datapengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_datasupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_databarangmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_databarangkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutActionPerformed
        login variable = new login();
        variable.show();
        dispose();
    }//GEN-LAST:event_button_logoutActionPerformed

    private void button_datasupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_datasupplierActionPerformed
        supplier variable = new supplier();
        variable.show();
        dispose();
    }//GEN-LAST:event_button_datasupplierActionPerformed

    private void button_datatransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_datatransaksiActionPerformed
        laporan_transaksi variable =  new laporan_transaksi();
        variable.show();
        dispose();
    }//GEN-LAST:event_button_datatransaksiActionPerformed

    private void button_databarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_databarangActionPerformed
        data_barang variable =  new data_barang();
        variable.show();
        dispose();
    }//GEN-LAST:event_button_databarangActionPerformed

    private void button_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_transaksiActionPerformed
        transaksi variable = new transaksi();
        variable.show();
        dispose();
    }//GEN-LAST:event_button_transaksiActionPerformed

    private void button_datapenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_datapenggunaActionPerformed
        data_pengguna variable = new data_pengguna();
        variable.show();
        dispose();
    }//GEN-LAST:event_button_datapenggunaActionPerformed

    private void button_databarangmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_databarangmasukActionPerformed
        laporan_barangmasuk variable = new laporan_barangmasuk();
        variable.show();
        dispose();
    }//GEN-LAST:event_button_databarangmasukActionPerformed

    private void button_databarangkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_databarangkeluarActionPerformed
        laporan_barangkeluar variable = new laporan_barangkeluar();
        variable.show();
        dispose();
    }//GEN-LAST:event_button_databarangkeluarActionPerformed

    private void button_opsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_opsiActionPerformed
        opsi_pembayaran variable =  new opsi_pembayaran();
        variable.show();
        dispose();
    }//GEN-LAST:event_button_opsiActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(admin.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_databarang;
    private javax.swing.JButton button_databarangkeluar;
    private javax.swing.JButton button_databarangmasuk;
    private javax.swing.JButton button_datapengguna;
    private javax.swing.JButton button_datasupplier;
    private javax.swing.JButton button_datatransaksi;
    private javax.swing.JButton button_logout;
    private javax.swing.JButton button_opsi;
    private javax.swing.JButton button_transaksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_level;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_tanggal;
    // End of variables declaration//GEN-END:variables
}
