/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsale;

import com.mysql.jdbc.Connection;
import java.io.File;
import java.io.FileWriter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author yanti
 */
public class laporan_barangmasuk extends javax.swing.JFrame {

    /**
     * Creates new form laporan_barangmasuk
     */
    Connection koneksi;
    public laporan_barangmasuk() {
        koneksi = DatabaseConnection.getKoneksi("localhost", "3306", "root", "", "db_pos");
        initComponents();
        LaporanBarangMasuk();
        total();
    }
    
    DefaultTableModel dtm;
    public void LaporanBarangMasuk(){
        String[] kolom = {"No","ID", "ID Barang", "Nama Barang", "Harga Beli", "Qty", "Sub Total", "Tanggal"};
        dtm = new DefaultTableModel(null, kolom);
        try{
            Statement stmt = koneksi.createStatement();
            String query = "SELECT * FROM barang_masuk";
            ResultSet rs =  stmt.executeQuery(query);
            int no = 1;
            while (rs.next()){
                String id = rs.getString("id");
                String id_barang = rs.getString("id_barang");
                String nama_barang = rs.getString("nama_barang");
                String harga_beli = rs.getString("harga_beli");
                String qty = rs.getString("qty");
                String subtotal = rs.getString("subtotal");
                String tanggal = rs.getString("tanggal");
                
                dtm.addRow(new String[]{no+"",id,id_barang,nama_barang,harga_beli,qty,subtotal,tanggal});
                no++;
            }
        }catch(SQLException ex) {
            ex.printStackTrace();
        }
        table_laporanbarangmasuk.setModel(dtm);
        
    }
    
    public void ExportToExcel(){
    FileWriter fileWriter;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("[B]export_output/excel[/B]"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try{
                TableModel tModel = table_laporanbarangmasuk.getModel();
                fileWriter = new FileWriter(new File(chooser.getSelectedFile() + ".xls"));           
            // write header
                for(int i = 0; i < tModel.getColumnCount(); i++){
                fileWriter.write(tModel.getColumnName(i).toUpperCase() + "\t");
            }
                fileWriter.write("\n");
            // write record
                for(int i=0; i < tModel.getRowCount(); i++) {
                for(int j=0; j < tModel.getColumnCount(); j++) {
                fileWriter.write(tModel.getValueAt(i,j).toString() + "\t");
            }
                fileWriter.write("\n");
            }
                fileWriter.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    
    public void total(){
        
        int jumlahBaris = table_laporanbarangmasuk.getRowCount();
        int totalBiaya = 0;
        int subtotal;
        TableModel tabelModel;
        tabelModel = table_laporanbarangmasuk.getModel();
        for (int i=0; i<jumlahBaris; i++){
            subtotal = Integer.parseInt(tabelModel.getValueAt(i, 6).toString());
            totalBiaya = totalBiaya + (subtotal);
        }
            text_total.setText(String.valueOf(totalBiaya));
    }
    
    public void HapusData(){
        String id = text_id.getText();
        try{
            // TODO add your handling code here:
            Statement stmt = koneksi.createStatement();
            String query = "DELETE FROM barang_masuk WHERE id = '"+id+"';";
            int berhasil = stmt.executeUpdate(query);
            if(berhasil == 1){
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!");
                dtm.getDataVector().removeAllElements();
                LaporanBarangMasuk();
            }else{
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus!");
            }
        }catch (SQLException ex){
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_laporanbarangmasuk = new javax.swing.JTable();
        button_hapus = new javax.swing.JButton();
        button_kembali = new javax.swing.JButton();
        text_id = new javax.swing.JTextField();
        text_total = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        button_ekspor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Laporan Barang Masuk");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 470, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        table_laporanbarangmasuk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        table_laporanbarangmasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_laporanbarangmasuk.setToolTipText("");
        table_laporanbarangmasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_laporanbarangmasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_laporanbarangmasuk);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1303;
        gridBagConstraints.ipady = 423;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 10);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        button_hapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_hapus.setText("Delete");
        button_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hapusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 6, 0, 0);
        getContentPane().add(button_hapus, gridBagConstraints);

        button_kembali.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_kembali.setText("Kembali");
        button_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_kembaliActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 6, 0, 10);
        getContentPane().add(button_kembali, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(52, 34, 0, 0);
        getContentPane().add(text_id, gridBagConstraints);

        text_total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 194;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 18, 38, 0);
        getContentPane().add(text_total, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 256, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        button_ekspor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_ekspor.setText("Ekspor");
        button_ekspor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_eksporActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 221, 0, 0);
        getContentPane().add(button_ekspor, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_kembaliActionPerformed
        dispose();
        admin variable = new admin();
        variable.show();
    }//GEN-LAST:event_button_kembaliActionPerformed

    private void button_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_hapusActionPerformed
        HapusData();
        LaporanBarangMasuk();
        total();
    }//GEN-LAST:event_button_hapusActionPerformed

    private void table_laporanbarangmasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_laporanbarangmasukMouseClicked
        int baris = table_laporanbarangmasuk.rowAtPoint(evt.getPoint());
        
        String id = table_laporanbarangmasuk.getValueAt(baris, 1).toString();
        text_id.setText(id);
    }//GEN-LAST:event_table_laporanbarangmasukMouseClicked

    private void button_eksporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_eksporActionPerformed
            ExportToExcel();
    }//GEN-LAST:event_button_eksporActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(laporan_barangmasuk.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan_barangmasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan_barangmasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan_barangmasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan_barangmasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan_barangmasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ekspor;
    private javax.swing.JButton button_hapus;
    private javax.swing.JButton button_kembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_laporanbarangmasuk;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_total;
    // End of variables declaration//GEN-END:variables
}
